# fly.toml app configuration file generated for ttttkazno on 2026-04-30T10:22:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ttttkazno'
primary_region = 'fra'

[build]

[env]
  TZ = 'Asia/Tashkent'

[processes]
  app = 'python obmen_bot.py'

[[mounts]]
  source = 'bot_data'
  destination = '/app/bot_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
